# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-20 22:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('vendors', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=250, null=True)),
                ('brand', models.CharField(max_length=50, null=True)),
                ('minimum', models.IntegerField(default=0)),
                ('maximum', models.IntegerField(default=9999999)),
                ('current', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
                ('vendors', models.ManyToManyField(to='vendors.Vendor')),
            ],
        ),
    ]
