# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-21 21:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0002_auto_20170421_1617'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendor',
            name='mailing_address_line_2',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
