# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-21 21:39
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0003_auto_20170421_1618'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendor',
            name='contact_email',
            field=models.CharField(default='', max_length=100, validators=[django.core.validators.EmailValidator()]),
        ),
    ]
