# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-21 22:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0005_auto_20170421_1647'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendor',
            name='website_address',
            field=models.CharField(default='', max_length=200),
        ),
    ]
